apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command:
        - /bin/sh
        - -c
        - echo "Running Nginx job"; sleep 5
      restartPolicy: Never
