name: KBOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

    #   - name: Docker Hub login
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: GitHub CR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build&Push
        env:
          APP: "kbot"
          CONTAINER_REGISTRY: ghcr.io
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update verion $VERSION"
          git push
